name: conchayoro-pipeline
on:p ush:
branches: [ main ]
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- uses: actions/upload-artifact@v2
with:
name: deploy
path: index.html
deploy:
runs-on: ubuntu-latest
needs: build
env:
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
AWS_EC2_METADATA_DISABLED: true
BUCKET: ${{ vars.BUCKET }}
steps:
- uses: actions/download-artifact@v2
with:
name: deploy
path: index.html
- run: aws s3 cp index.html s3://$BUCKET --recursive --acl
public-read
